#!/bin/sh

if [ "$#" -eq 1 ]; then
	VERSION="$1"
	shift
else
	echo "./make_release versao_nova" >&2
	exit 1
fi

IFS='.' read -r v_major v_minor v_patch < version.txt

case "$VERSION" in
	patch)
		VERSION="${v_major}.${v_minor}.$((v_patch + 1))"
	;;
	minor)
		VERSION="${v_major}.$((v_minor + 1)).0"
	;;
	major)
		VERSION="$((v_major + 1)).0.0"
	;;
esac

# echo new version: $VERSION
# exit 0
printf "%s" "$VERSION" > version.txt

git add -A
git commit -sm "bump to $VERSION"
if [ -z "${NO_TAG+x}" ]; then
	git tag "$VERSION"
	git push --tag
fi
git push
